_target_: gfm.models.FlowMapModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_epochs}
  eta_min: 1e-6

net:
  _target_: gfm.models.arch.rfm.TMLP
  d_model: 1024
  num_layers: 8
  actfn: swish
  d_in: 9

in_shape:
  - 9

# compile model for faster training with pytorch 2.0
compile: false
manifold: so3
underlying_loss: lsd
fm_loss_weight: 1.0
so3_plot: True